### ISSUE TITLE
Missing client classes on right-click on Forge server

### ISSUE THREAD

**Issue by haykam821** [TheRealZeher/DimensionalPockets-II#27]
Every time I right-click the dimensional pocket block, this error appears in the log:

```
[21:53:23] [Server thread/INFO] [dimensionalpocketsii]: [INFO] Pocket: [BlockPos{x=2, y=0, z=2}] Already contains that BlockPos. No update to the Map.
[21:53:23] [Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_211]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
	at com.zeher.dimensionalpockets.core.util.DimUtils.enforceServer(DimUtils.java:173) ~[DimUtils.class:?]
	at com.zeher.dimensionalpockets.core.dimshift.DimensionalShifter.<init>(DimensionalShifter.java:24) ~[DimensionalShifter.class:?]
	at com.zeher.dimensionalpockets.core.dimshift.DimensionalShiftUtils.createTeleporter(DimensionalShiftUtils.java:13) ~[DimensionalShiftUtils.class:?]
	at com.zeher.dimensionalpockets.pocket.Pocket.shiftTo(Pocket.java:179) ~[Pocket.class:?]
	at com.zeher.dimensionalpockets.pocket.tileentity.TileEntityDimensionalPocket.shiftIntoPocket(TileEntityDimensionalPocket.java:299) ~[TileEntityDimensionalPocket.class:?]
	at com.zeher.dimensionalpockets.pocket.tileentity.TileEntityDimensionalPocket.onBlockActivated(TileEntityDimensionalPocket.java:178) ~[TileEntityDimensionalPocket.class:?]
	at com.zeher.dimensionalpockets.pocket.block.BlockDimensionalPocket.func_180639_a(BlockDimensionalPocket.java:57) ~[BlockDimensionalPocket.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449) ~[or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_211]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 5 more
```

Obviously, the dimensional pocket block never sends me to the pocket dimension.

**Comment by TheRealZeher** [comment]
Hi, could you post a mod list that you used when the error occured please?

**Comment by haykam821** [comment]
Sorry, here's the modlist (in addition to Minecraft **1.12.2** and Forge **14.23.5.2838**):

![Modlist from MultiMC](https://user-images.githubusercontent.com/24855774/60385199-99379d80-9a54-11e9-89dc-36c2472e5b5c.png)

**Comment by TheRealZeher** [comment]
I see the issue, you need to update Dimensional pockets to the latest version, 2.0.14-beta. You are using in compatible versions of dimensional pockets and TRZLib

**Comment by haykam821** [comment]
I am using the downloaded jar with the name `dimensionalpocketsii-1.12.2-2.0.14-beta-universal.jar`. The version shown in my mod list appears to be `1.2.10-beta` instead.

**Comment by TheRealZeher** [comment]
Ok I'll take a further look into it.

**Comment by Eidenz** [comment]
I have the same error, but reading the error log explains everything : the mod is looking for a CLIENT class in the SERVER files. You are calling client side classes in your mod, making it incompatible with forge servers.

**Comment by haykam821** [comment]
That makes sense; I'm using a server too. I have updated the issue title to reflect the cause.

**Comment by TheRealZeher** [comment]
This issue has been fixed. There was some legacy code being run from a client class.
