### ISSUE TITLE
[1.18.2] client game crashes after spawning in pocket in existing world

### ISSUE THREAD

**Issue by DragonKiller952** [TheRealZeher/DimensionalPockets-II#94]
I was playing the game normally with entering and leaving the pocket just fine, but when I closed the world while in the pocket and re-opened it, it spawned me into the pocket but crashed after a few seconds.

im using cosmos library 6.3.0.0 and DP2 version 6.1.2.0

I was also playing with OptiFine, but even after removing it the game crashes the same way

<details>
  <summary>Crash Log:</summary>
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 8/6/22, 3:05 PM
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "com.tcn.dimensionalpocketsii.pocket.core.gson.PocketChunkInfo.getDominantChunk()" because "this.chunk_info" is null
	at com.tcn.dimensionalpocketsii.pocket.core.Pocket.getDominantChunkPos(Pocket.java:393) ~[dimensionalpocketsii-1.18.2-6.1.2.0-universal.jar%2359!/:1.18.2-6.1.2.0-universal] {re:classloading}
	at com.tcn.dimensionalpocketsii.pocket.core.Pocket.updateBaseConnector(Pocket.java:1091) ~[dimensionalpocketsii-1.18.2-6.1.2.0-universal.jar%2359!/:1.18.2-6.1.2.0-universal] {re:classloading}
	at com.tcn.dimensionalpocketsii.pocket.core.blockentity.BlockEntityModuleConnector.sendUpdates(BlockEntityModuleConnector.java:122) ~[dimensionalpocketsii-1.18.2-6.1.2.0-universal.jar%2359!/:1.18.2-6.1.2.0-universal] {re:classloading}
	at com.tcn.dimensionalpocketsii.pocket.core.blockentity.BlockEntityModuleConnector.tick(BlockEntityModuleConnector.java:369) ~[dimensionalpocketsii-1.18.2-6.1.2.0-universal.jar%2359!/:1.18.2-6.1.2.0-universal] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46463_(Level.java:475) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:118) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.tcn.dimensionalpocketsii.pocket.core.Pocket.getDominantChunkPos(Pocket.java:393) ~[dimensionalpocketsii-1.18.2-6.1.2.0-universal.jar%2359!/:1.18.2-6.1.2.0-universal] {re:classloading}
	at com.tcn.dimensionalpocketsii.pocket.core.Pocket.updateBaseConnector(Pocket.java:1091) ~[dimensionalpocketsii-1.18.2-6.1.2.0-universal.jar%2359!/:1.18.2-6.1.2.0-universal] {re:classloading}
	at com.tcn.dimensionalpocketsii.pocket.core.blockentity.BlockEntityModuleConnector.sendUpdates(BlockEntityModuleConnector.java:122) ~[dimensionalpocketsii-1.18.2-6.1.2.0-universal.jar%2359!/:1.18.2-6.1.2.0-universal] {re:classloading}
	at com.tcn.dimensionalpocketsii.pocket.core.blockentity.BlockEntityModuleConnector.tick(BlockEntityModuleConnector.java:369) ~[dimensionalpocketsii-1.18.2-6.1.2.0-universal.jar%2359!/:1.18.2-6.1.2.0-universal] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46463_(Level.java:475) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A}
-- Block entity being ticked --
Details:
	Name: dimensionalpocketsii:tile_entity_connector // com.tcn.dimensionalpocketsii.pocket.core.blockentity.BlockEntityModuleConnector
	Block: Block{dimensionalpocketsii:block_wall_connector}[mode=0,type=0]
	Block location: World: (7,3,14), Section: (at 7,3,14 in 0,0,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Block: Block{dimensionalpocketsii:block_wall_connector}[mode=0,type=0]
	Block location: World: (7,3,14), Section: (at 7,3,14 in 0,0,0; chunk contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Stacktrace:
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_46463_(Level.java:475) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:118) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['DragonKiller952'/30, l='ServerLevel[New World of Pollution]', x=9.95, y=2.00, z=6.95]]
	Chunk stats: 12960
	Level dimension: dimensionalpocketsii:pocket
	Derived: true
	Level spawn location: World: (-304,76,112), Section: (at 0,12,0 in -19,4,7; chunk contains blocks -304,0,112 to -289,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 46403 game time, 46403 day time
	Level name: New World of Pollution
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Level weather: Rain time: 119806 (now: false), thunder time: 30488 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:118) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%2372!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Mac OS X (x86_64) version 12.4
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1942703960 bytes (1852 MiB) / 3841982464 bytes (3664 MiB) up to 8489271296 bytes (8096 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: Intel UHD Graphics 630
	Graphics card #0 vendor: Intel
	Graphics card #0 VRAM (MB): 1536.00
	Graphics card #0 deviceId: 0x3e9b
	Graphics card #0 versionInfo: Revision ID: 0x0002, gMux Version: 5.0.0
	Graphics card #1 name: Radeon Pro 560X
	Graphics card #1 vendor: AMD (0x1002)
	Graphics card #1 VRAM (MB): 4096.00
	Graphics card #1 deviceId: 0x67ef
	Graphics card #1 versionInfo: Revision ID: 0x00c2, ROM Revision: 113-C980AL-075, VBIOS Version: 113-C97501U-005, EFI Driver Version: 01.A1.075, gMux Version: 5.0.0
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18432.00
	Virtual memory used (MB): 11993.98
	Swap memory total (MB): 2048.00
	Swap memory used (MB): 1279.75
	JVM Flags: 3 total; -Xss1M -Xmx8096m -Xms256m
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['DragonKiller952'/30, l='ServerLevel[New World of Pollution]', x=9.95, y=2.00, z=6.95]]
	Data Packs: vanilla, mod:storagenetwork (incompatible), mod:sophisticatedbackpacks (incompatible), mod:immersiveengineering, mod:jade, mod:architectury (incompatible), mod:ftblibrary (incompatible), mod:jei (incompatible), mod:projecte, mod:ftbteams (incompatible), mod:ftbchunks (incompatible), mod:forge, mod:sophisticatedcore (incompatible), mod:curios (incompatible), mod:curiouslights, mod:forgeendertech, mod:adpother, mod:adchimneys, mod:shutupexperimentalsettings, mod:dimensionalpocketsii, mod:cosmoslibrary
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	OptiFine Version: OptiFine_1.18.2_HD_U_H7
	OptiFine Build: 20220410-185216
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.1 ATI-4.8.54
	OpenGlRenderer: AMD Radeon Pro 560X OpenGL Engine
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 16
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 OptiFine TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		SimpleStorageNetwork-1.18.2-1.6.2.jar             |Simple Storage Network        |storagenetwork                |1.18.2-1.6.2        |DONE      |Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		sophisticatedbackpacks-1.18.2-3.18.16.671.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.2-3.18.16.671  |DONE      |Manifest: NOSIGNATURE
		ImmersiveEngineering-1.18.2-8.1.0-150.jar         |Immersive Engineering         |immersiveengineering          |1.18.2-8.1.0-150    |DONE      |Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		Jade-1.18.2-forge-5.2.3.jar                       |Jade                          |jade                          |5.2.3               |DONE      |Manifest: NOSIGNATURE
		architectury-4.7.78-forge.jar                     |Architectury                  |architectury                  |4.7.78              |DONE      |Manifest: NOSIGNATURE
		ftb-library-forge-1802.3.6-build.140.jar          |FTB Library                   |ftblibrary                    |1802.3.6-build.140  |DONE      |Manifest: NOSIGNATURE
		jei-1.18.2-9.7.1.232.jar                          |Just Enough Items             |jei                           |9.7.1.232           |DONE      |Manifest: NOSIGNATURE
		ProjectE-1.18.2-PE1.0.1.jar                       |ProjectE                      |projecte                      |1.0.1               |DONE      |Manifest: NOSIGNATURE
		ftb-teams-forge-1802.2.6-build.51.jar             |FTB Teams                     |ftbteams                      |1802.2.6-build.51   |DONE      |Manifest: NOSIGNATURE
		ftb-chunks-forge-1802.3.6-build.147.jar           |FTB Chunks                    |ftbchunks                     |1802.3.6-build.147  |DONE      |Manifest: NOSIGNATURE
		forge-1.18.2-40.1.48-universal.jar                |Forge                         |forge                         |40.1.48             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		sophisticatedcore-1.18.2-0.4.11.89.jar            |Sophisticated Core            |sophisticatedcore             |1.18.2-0.4.11.89    |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.7.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.1      |DONE      |Manifest: NOSIGNATURE
		curiouslights-forge-1.2.0+1.18.2.jar              |Curious Lights                |curiouslights                 |1.2.0+1.18.2        |DONE      |Manifest: NOSIGNATURE
		ForgeEndertech-1.18.2-9.0.4.0-build.1016.jar      |ForgeEndertech                |forgeendertech                |9.0.4.0             |DONE      |Manifest: NOSIGNATURE
		AdPother-1.18.2-6.0.5.0-build.1034.jar            |Pollution of the Realms       |adpother                      |6.0.5.0             |DONE      |Manifest: NOSIGNATURE
		AdChimneys-1.18.2-8.3.1.0-build.1034.jar          |Advanced Chimneys             |adchimneys                    |8.3.1.0             |DONE      |Manifest: NOSIGNATURE
		shutupexperimentalsettings-1.0.5.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.5               |DONE      |Manifest: NOSIGNATURE
		dimensionalpocketsii-1.18.2-6.1.2.0-universal.jar |Dimensional Pockets II        |dimensionalpocketsii          |6.1.2.0             |DONE      |Manifest: NOSIGNATURE
		cosmoslibrary-1.18.2-6.3.0.0-universal.jar        |Cosmos Library                |cosmoslibrary                 |6.3.0.0             |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 3f94949d-f138-4a1c-9c79-b8b3d18b537a
	FML: 40.1
	Forge: net.minecraftforge:40.1.48

</details>

**Comment by TheCosmicNebula** [comment]
Ah I think I know what the error is. I will take a look into this in the next few days.

**Comment by DragonKiller952** [comment]
Any update on this issue?

**Comment by TheCosmicNebula** [comment]
I haven't had time till now, but I have been updating my mods to 1.19.1. I will look into this issue tonight.

**Comment by navyglobe** [comment]
im having this same issue let plz let me know if you find a fix

**Comment by navyglobe** [comment]
Yo i figured it out and got it to work. all you have to do is go into your world folder and delete the dimpockets folder, when u load the world up it should work the only thing is the portal pocket block wont be under your ownership so u cant get rid of it

**Comment by TheCosmicNebula** [comment]
I am investigating the issue at the moment. I hope to have a fix soon.

**Comment by TheCosmicNebula** [comment]
I have discovered a MAJOR bug with the last 1.18.2 release, causing Pocket data to be lost forever. I am issuing a new version today to at least stop the crashing and buggy behaviour, however any worlds used on the older versions will have lost their Pocket information forever. I can only apologize for this error, I did not experience any of this when testing the mod in my Development environment.

**Comment by TheCosmicNebula** [comment]
Fixed this issue as per release 6.1.3.40. 

I apologize again, as it will not be able to recover lost items, pockets or contents, but it will not break any worlds going forward, so if you have backups, you can use those to restore your progress. You can use your existing world and copy across a file but that requires detailed instructions, so if you need that please PM me.

**Comment by TheCosmicNebula** [comment]
https://www.curseforge.com/minecraft/mc-mods/dimensional-pockets-ii/files/4000027

The new release will be available here shortly.

**Comment by DragonKiller952** [comment]
I created a new world to check it out, and the crashing problem seems to have been fixed! however the problem now is that it says I am not the owner. when I re-enter the pocket it returns back to normal, but I think this is not supposed to happen

**Comment by TheCosmicNebula** [comment]
Yes unfortunately the bug within the code deleted the information related to the Pocket when used. There is no way to recover this information. Apologies for the inconvenience, I did not experience any of the issues when testing and allowed the bug to be released.

**Comment by DragonKiller952** [comment]
so I will have to re-enter the pockets each time I open the world? cause that is what is currently happening at least.

**Comment by TheCosmicNebula** [comment]
You should only have to enter the Pocket once and it should generate new information as if it was a brand new Pocket. If you are having to enter it to claim it everytime you open the world then I need to look into that.

**Comment by DragonKiller952** [comment]
yeah like I said, I created a brand new world to test the fix, and every time I close the world and open it I have to re-enter them or enter them before I can interact with the settings and such because it tells me I'm not allowed

**Comment by TheCosmicNebula** [comment]
I will look into this this evening

**Comment by TheCosmicNebula** [comment]
Issue fixed as per Releases: 6.1.3.60 [1.18.2], 7.1.1.40 [1.19.1]
